<?php
return array(
    "authorize" => "main/authorize",
    "users" => "main/users",
    "friends" => "main/friend",
    "register" => "main/register",
    "feedpost" => "main/feedpost",
    "profileinfo" => "main/profileinfo",
    "myposts" => "main/myposts",
    "createpost" => "main/createpost",
    "userprofile" => "main/userprofile",
    "messages" => "main/messages",
    "sendmessage" => "main/sendmessage",
    "createdialog" => "main/createdialog",
    "search" => "main/search",
    "addfriend" => "main/addfriend",
    "creategroup" => "main/creategroup",
    "getusergroup" => "main/getusergroup",
    "getgroup" => "main/getgroup",
    "deletepost" => "main/deletepost",
    "deletemessagegroup" => "main/deletemessagegroup",
    "deletefriend" => "main/deletefriend",
    "deletemessage" => "main/deletemessage",
    "creategroup" => "main/creategroup"
);
